[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_API_URL = "https://signature-opal.netlify.app"
  VITE_SUPABASE_URL = "https://midnphgicryyoeubulro.supabase.co"
  VITE_SUPABASE_ANON_KEY = "<YOUR_SUPABASE_ANON_KEY>"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
